config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'movies/youga' => 'movies#youga'
  get 'movies/houga' => 'movies#houga'
  get 'movies/about' => 'movies#about'
  resources :users, only: [:show]  
  resources :movies do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end 
  resources :tweets
  root 'movies#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :user 
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :movie_tag_relations, dependent: :destroy
    has_many :tags, through: :movie_tag_relations, dependent: :destroy
    mount_uploader :image, ImageUploader
end

app/models/movie_tag_relation.rb
class MovieTagRelation < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :movie_tag_relations, dependent: :destroy
    has_many :movies, through: :movie_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  
        has_many :movies, dependent: :destroy 
        has_many :likes, dependent: :destroy
        has_many :liked_movies, through: :likes, source: :movie
        has_many :comments, dependent: :destroy

        def already_liked?(movie)
          self.likes.exists?(movie_id: movie.id)
        end
        
        validates :name, presence: true 
        validates :profile, length: { maximum: 200 } 
        mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        movie = Movie.find(params[:movie_id])
        comment = movie.comments.build(comment_params) 
        comment.user_id = current_user.id
        if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) 
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) 
        end
    end

    private

        def comment_params
            params.require(:comment).permit(:content)
        end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(movie_id: params[:movie_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(movie_id: params[:movie_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def top
        @movies = Movie.all
        @movies = Movie.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    end

    def youga
        @movies = Movie.all
        @movies = Movie.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    end

    def houga
        @movies = Movie.all
        @movies = Movie.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    end

    def about
    end

    def index
        @movies = Movie.all
        if params[:search] == nil
            @movies= Movie.all
        elsif params[:search] == ''
            @movies= Movie.all
        else
            @movies = Movie.where("title LIKE ? ",'%' + params[:search] + '%')
        end
        if params[:tag_ids]
            @movies = []
            params[:tag_ids].each do |key, value|      
                @movies += Tag.find_by(name: key).movies if value == "1"
            end
            @movies.uniq!
        end
        
    end

    def new
        @movie = Movie.new
    end

    def create
        movie = Movie.new(movie_params)
        movie.user_id = current_user.id
        if movie.save!
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @movie = Movie.find(params[:id])
        @comments = @movie.comments
        @comment = Comment.new
    end
    
    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        movie = Movie.find(params[:id])
        if movie.update(movie_params)
            redirect_to :action => "show", :id => movie.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        movie = Movie.find(params[:id])
        movie.destroy
        redirect_to action: :index
    end

    private
    def movie_params
        params.require(:movie).permit(:title, :highlight, :released_year, :image, :main_character, :user_id, :body, tag_ids: [])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
    end

    def new
        @tweet = Tweet.new
    end

    def show
        @tweet = Tweet.find_by(id: params[:id])
    end

    def create
        @tweet = Tweet.new(tweet_params)
        params[:tweet][:question] ? @tweet.question = params[:tweet][:question].join("") : false
        if @tweet.save
            flash[:notice] = "診断が完了しました"
            redirect_to tweet_path(@tweet.id)
        else
            redirect_to :action => "new"
        end
    end

private
    def tweet_params
        params.require(:tweet).permit(:id, question: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disc_helper.rb
module DiscHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movies/edit.html.erb
<%= form_for @movie do |f| %>
    <% if user_signed_in? %>
        <div  class= "edit" >
            <%= f.label :title %>
            <%= f.text_field :title, :size => 30 %> 
            <%= f.label :highlight %>
            <%= f.text_field :highlight, :size => 30 %> 
            <%= f.label :released_year %>
            <%= f.text_field :released_year, :size => 30 %> 
            <%= f.label :maincharacter %>
            <%= f.text_field :maincharacter, :size => 30 %> 
        <%= f.submit "編集する" %>
        </div>
    <% end %>
<% end %>

app/views/movies/houga.html.erb
<div class="movies-container">
    <% @movies.each_with_index do |t,i| %>
        <% if i < 3 %>
        第<%= i+1 %>位
        <% if t.tags.exists?(name: '邦画')%>

    < class="movie">
        <%= link_to t.user.name, user_path(t.user.id) %> 
        <p>タイトル</p>
        <%= t.title %>
        <p>公開年</p>
        <%= t.released_year %>
        <p>あらすじ</p>
        <%= t.highlight %>
        <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
                <%= button_to movie_like_path(id: t.id, movie_id: t.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% else %>
                <%= button_to movie_likes_path(id: t.id, movie_id: t.id), method: :post do %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% end %>
        <% else %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
        <%= link_to "詳細へ", movie_path(t.id) %> 
        <% if user_signed_in? && current_user.id == t.user_id %>
            <%= button_to "削除", movie_path(t.id), method: :delete %>
            <%= link_to "編集", edit_movie_path(t.id) %>
        <% end %>
        <% end %>
    </div>
        <% end %>
<% end %>

app/views/movies/index.html.erb
<div class="movie5">
    <div class="movies-kaito">
    <h3>一覧ページ</h3>
    </div>

<div class="search">
<h3>投稿を検索</h3>
    <%= form_tag({controller:"movies",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索' %>
    <% end %>
</div>

<h4>タグを検索</h4>
<div class="movies-ami">
    <%= form_tag({controller:"movies",action:"index"}, method: :get) do %>
        <% Tag.all.each do |t| %>
            <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
        <% end %>
        <%= submit_tag '検索' %>
    <% end %>

<div class="movies-container">
    <% @movies.each do |t| %>
        <div class="movie1">
            <%= link_to t.user.name, user_path(t.user.id) %>     
            <p>『タイトル』</p>
            <%= t.title %>
            <p>『公開年』</p>
            <%= t.released_year %>
            <p>『あらすじ』</p>
            <%= t.highlight %>
                <div class="index">
                    <% if user_signed_in? %>
                        <% if current_user.already_liked?(t) %>
                            <%= button_to movie_like_path(id: t.id, movie_id: t.id), method: :delete do %>
                                <i class="fas fa-heart"></i><%= t.likes.count %>
                            <% end %>
                        <% else %>
                            <%= button_to movie_likes_path(id: t.id, movie_id: t.id), method: :post do %>
                                <i class="fas fa-heart"></i><%= t.likes.count %>
                            <% end %>
                        <% end %>
                    <% else %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %>
                    <%= link_to "詳細へ", movie_path(t.id) %> 
                    <% if user_signed_in? && current_user.id == t.user_id then %>
                        <%= button_to "削除", movie_path(t.id), method: :delete %>
                        <%= link_to "編集", edit_movie_path(t.id) %>
                    <% end %>
                </div>
        </div>
    <% end %>
</div>
</div>
</div>

app/views/movies/new.html.erb
<h3>新規投稿ページ</h3>
<div class="movie-new">
<%= form_for @movie do |f| %>
    <div class='form-group'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
        <div class='form-check'>
            <%= tag.label class: 'form-check-label' do %>
                <%= tag.check_box class: 'form-check-input' %>
                <%= tag.text %>
            <% end %>
        </div>
    <% end %>
    </div>
    
    <div class ="fields">
        <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, :size => 30 %>
        </div>

        <div class="field">
            <%= f.label :released_year  %>
            <%= f.number_field :released_year, :size => 10 %>
        </div>

        <div class="field">
        <%= f.label :maincharacter %>
        <%= f.text_field :maincharacter, :size => 30 %>
        </div>

        <div class="field">
            <%= f.label :highlight  %>
            <%= f.text_area :highlight, :size => "30x2" %>
        </div>

    <%= f.submit "投稿する" %>
    </div>
</div>
<% end %>

app/views/movies/show.html.erb
<h3>詳細</h3>
<div class="movie">
  <p><%= link_to @movie.user.name, user_path(@movie.user.id) %></p>
  <p>『公開年』</p>
  <p><%= @movie.released_year %></p>
  <p>『タイトル』</p>
  <p><%= @movie.title %></p>
  <p>『あらすじ』</p>
  <p><%= @movie.highlight %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@movie) %>
        <%= button_to movie_like_path(@movie), method: :delete do %>
          <i class="far fa-heart"></i><%= @movie.likes.count %>
        <% end %>
      <% else %>
        <%= button_to movie_likes_path(@movie), method: :post do %>
          <i class="far fa-heart"></i><%= @movie.likes.count %>
        <% end %>
    <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @movie.likes.count %>
    <% end %>
    <% @movie.tags.each do |tag| %>
      <span><%= tag.name %></span>
    <% end %>
</div>

<h2>いいねしたユーザー</h2>
<div class="good">
<% @movie.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</div>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
      <%= form_with(model: [@movie, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
  <% end %>
</div>
<% if user_signed_in?  && current_user.id == @movie.user.id then %>
    <%= link_to "編集", edit_movie_path(@movie.id) %>
<% end %>

app/views/movies/top.html.erb
<div class="search">
<%= form_tag({controller:"movies",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索' %>
<% end %>
</div>

<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<title>6-1-7 複数画像を中央に注目させて見せる</title>
<meta name="description"  content="書籍「動くWebデザインアイディア帳」のサンプルサイトです">

<meta name="viewport" content="width=device-width,initial-scale=1.0">
<!--==============レイアウトを制御する独自のCSSを読み込み===============-->
<link rel="stylesheet" type="text/css" href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/reset.css">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css">
<link rel="stylesheet" type="text/css" href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-1-7/css/6-1-7.css">

</head>

<body>

<ul class="slider">
    <li><img src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-1-7/img/img_01.jpg" alt=""></li>
    <li><img src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-1-7/img/img_02.jpg" alt=""></li>
    <li><img src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-1-7/img/img_03.jpg" alt=""></li>
    <li><img src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-1-7/img/img_04.jpg" alt=""></li>
    <li><img src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-1-7/img/img_05.jpg" alt=""></li>
    <li><img src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-1-7/img/img_06.jpg" alt=""></li>
<!--/slider--></ul>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<script src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/6-1-7/js/6-1-7.js"></script>

</body>
</html>

<div class= "movie-top">
    <div class= "movie-top1">
        <%= form_tag({controller:"movies",action:"index"}, method: :get) do %>
            <% Tag.all.each do |t| %>
                <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
            <% end %>
            <%= submit_tag '検索' %>
        <% end %>
    </div>

<div class="movies-container">
    <% @movies.each_with_index do |t,i| %>
        <% if i < 3 %>
        第<%= i+1 %>位
        <div class="movie">
            <%= link_to t.user.name, user_path(t.user.id) %>
            <%= image_tag t.image_url, size: "250x200" if t.image? %>   
            <p>『タイトル』</p>
            <%= t.title %>
            <p>『公開年』</p>
            <%= t.released_year %>
            <p>『あらすじ』</p>
            <%= t.highlight %>
            <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                <% else %>
                        <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% else %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        </div>
        <% end %>
    <% end %>
</div>
</div>

<script>
$('.slider').slick({
    autoplay: true,//自動的に動き出すか。初期値はfalse。
    infinite: true,//スライドをループさせるかどうか。初期値はtrue。
    speed: 500,//スライドのスピード。初期値は300。
    slidesToShow: 3,//スライドを画面に3枚見せる
    slidesToScroll: 1,//1回のスクロールで1枚の写真を移動して見せる
    prevArrow: '<div class="slick-prev"></div>',//矢印部分PreviewのHTMLを変更
    nextArrow: '<div class="slick-next"></div>',//矢印部分NextのHTMLを変更
    centerMode: true,//要素を中央ぞろえにする
    variableWidth: true,//幅の違う画像の高さを揃えて表示
    dots: true,//下部ドットナビゲーションの表示
});
</script>

app/views/movies/youga.html.erb
<div class="movies">
    <% @movies.each_with_index do |t,i| %>
        <% if i < 3 %>
        第<%= i+1 %>位
        <% if t.tags.exists?(name: '洋画')%>

    <div class="movie2">
        <%= link_to t.user.name, user_path(t.user.id) %>     
        <p>『タイトル』</p>
        <%= t.title %>
        <p>『公開年』</p>
        <%= t.released_year %>
        <p>『あらすじ』</p>
        <%= t.highlight %>
        <div class="index">
        <% if user_signed_in? %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
        <%= link_to "詳細へ", movie_path(t.id) %> 
        <% if user_signed_in? && current_user.id == t.user_id %>
            <%= button_to "削除", movie_path(t.id), method: :delete %>
            <%= link_to "編集", edit_movie_path(t.id) %>
        <% end %>
        <% end %>
        </div>
    </div>
        <% end %>
<% end %>
</div>

app/views/tweets/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>香水診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a></a>
            </h1>
            <ul class="nav-list">
                
            </ul>
        </header>

        <div class="start">
            <h4>Are you ready?</h4>
            <%= link_to "診断を始める", new_tweet_path, class: "link" %>
        </div>
    </body>
    <%= link_to "トップページへ", root_path %>

app/views/tweets/new.html.erb
<%= form_for(@tweet, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="sindan">
        <div class="sindan1">
            <div class="col-12">
                <p>Question1. どちらが好きか？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>洋画</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>邦画</p>
            </div>
        </div>
        <div class="sindan2">
            <div class="col-12">
                <p>Question2. 今日の気分は？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>ドキドキしたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>キュンキュンしたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "3", nil %>思いっきり泣きたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "4", nil %>スカッとしたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "5", nil %>笑いたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "6", nil %>元気をもらいたい</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "送信" %>
    </div>
<% end %>

app/views/tweets/show.html.erb
<div class="intoro">
<h3>診断結果</h3>
<p>あなたにおすすめの映画は…</p>
</div>
<div class="movie-container">
<div class="movie">
    <% if @tweet.question == "11" %>
    <h3>レモン</h3>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>

    <% elsif @tweet.question == "12" %>
    <h3>シトラス</h3>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>

    <% elsif @tweet.question == "13" %>
    <h3>ローズ</h3>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>

    <% elsif @tweet.question == "14" %>
    <h3>『エクスペンダブルズ』(2010年)</h3>
    <p>あらすじ</p>
    <p>CIAから難解な任務を課されるエリート傭兵部隊「エクスペンダブルズ」。彼らは南米の島を武力制圧しているガルザ将軍を暗殺する任務を請け負う。しかし、下調べをしている際に出会った反政府活動に協力するカサンドラが将軍の娘と知り、任務が混迷を極めていき……。</p>

    <% elsif @tweet.question == "15" %>
    <h3>ジャスミン</h3>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>

    <% elsif @tweet.question == "16" %>
    <h3></h3>
    <p></p>
    <p></p>

    <% elsif @tweet.question == "21" %>
    <h3>アップル</h3>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>

    <% elsif @tweet.question == "22" %>
    <h3>ユーカリ</h3>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

    <% elsif @tweet.question == "23" %>
    <h3>ローズマリー</h3>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>

    <% elsif @tweet.question == "24" %>
    <h3>ベルガモット</h3>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>

    <% elsif @tweet.question == "25" %>
    <h3>ムスク</h3>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>

    <% elsif @tweet.question == "26" %>
    <h3>アンバー</h3>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>

    <% end %>

</div>
<%= link_to "トップページへ", root_path %>
<%= link_to "一覧に戻る", movies_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
    <%= image_tag @user.image_url, size: "250x200" if @user.image? %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.movies.each do |t| %>
    <%= t.user.name %>
    <%= t.title %>
    <%= t.highlight %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_movies.each do |t| %>
    <%= t.user.name %>
    <p>『タイトル』</p>
    <%= t.title %>
    <p>『あらすじ』</p>
    <%= t.highlight %>
<% end %>
<!-- ここまで-->