config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'movies/youga' => 'movies#youga'
  get 'movies/houga' => 'movies#houga'
  get 'movies/about' => 'movies#about'
  resources :users, only: [:show]  
  resources :movies do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end 
  resources :tweets
  root 'movies#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :user 
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :movie_tag_relations, dependent: :destroy
    has_many :tags, through: :movie_tag_relations, dependent: :destroy
    mount_uploader :image, ImageUploader
end

app/models/movie_tag_relation.rb
class MovieTagRelation < ApplicationRecord
  belongs_to :movie
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :movie_tag_relations, dependent: :destroy
    has_many :movies, through: :movie_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  
        has_many :movies, dependent: :destroy 
        has_many :likes, dependent: :destroy
        has_many :liked_movies, through: :likes, source: :movie
        has_many :comments, dependent: :destroy

        def already_liked?(movie)
          self.likes.exists?(movie_id: movie.id)
        end
        
        validates :name, presence: true 
        validates :profile, length: { maximum: 200 } 
        mount_uploader :image, ImageUploader
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(movie_id: params[:movie_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(movie_id: params[:movie_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def top
        @movies = Movie.all
        @movies = Movie.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    end

    def youga
        @movies = Movie.all
        @movies = Movie.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    end

    def houga
        @movies = Movie.all
        @movies = Movie.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    end

    def about
    end

    def index
        @movies = Movie.all
        if params[:search] == nil
            @movies= Movie.all
        elsif params[:search] == ''
            @movies= Movie.all
        else
            @movies = Movie.where("title LIKE ? ",'%' + params[:search] + '%')
        end
        if params[:tag_ids]
            @movies = []
            params[:tag_ids].each do |key, value|      
                @movies += Tag.find_by(name: key).movies if value == "1"
            end
            @movies.uniq!
        end
        
    end

    def new
        @movie = Movie.new
    end

    def create
        movie = Movie.new(movie_params)
        movie.user_id = current_user.id
        if movie.save!
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @movie = Movie.find(params[:id])
        @comments = @movie.comments
        @comment = Comment.new
    end
    
    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        movie = Movie.find(params[:id])
        if movie.update(movie_params)
            redirect_to :action => "show", :id => movie.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        movie = Movie.find(params[:id])
        movie.destroy
        redirect_to action: :index
    end

    private
    def movie_params
        params.require(:movie).permit(:title, :highlight, :released_year, :image, :main_character, :user_id, :body, tag_ids: [])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
    end

    def new
        @tweet = Tweet.new
    end

    def show
        @tweet = Tweet.find_by(id: params[:id])
    end

    def create
        @tweet = Tweet.new(tweet_params)
        params[:tweet][:question] ? @tweet.question = params[:tweet][:question].join("") : false
        if @tweet.save
            flash[:notice] = "診断が完了しました"
            redirect_to tweet_path(@tweet.id)
        else
            redirect_to :action => "new"
        end
    end

private
    def tweet_params
        params.require(:tweet).permit(:id, question: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disc_helper.rb
module DiscHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yukimovie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/61fc49be1f.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
  <header>
  <div class="header-logo">
    <h1>Yukimovie</h1>
  </div>
  <div class="openbtn"><span></span><span></span><span></span></div>
  <nav id="g-nav">
    <div id="g-nav-list">  
      <ul class="gnavi">
        <li class="current" >
          <%= link_to "top" , root_path %>
        </li>  
        <li> 
          <%=link_to "about", movies_about_path %> 
        </li> 
        <li>
          <%= link_to "投稿一覧", movies_path %>
        </li>
        <li>
          <%=link_to "診断", tweets_path %>
        </li>
        <li>
          <%=link_to "新規投稿", new_movie_path %>
        </li>
        <li>
          <%= link_to "洋画ランキングへ", movies_youga_path %>
        </li>
        <li>
          <%= link_to "邦画ランキングへ", movies_houga_path %>
        </li>
        <li> 
          <% if user_signed_in? %>
            <%= link_to "my page", user_path(current_user.id) %>
              <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "log in", user_session_path %>
            <%= link_to "sign up", new_user_registration_path %>"
          <% end %>
        </li> 
      </ul>  
    </div>
  </nav>
  </header>
  <main>
    <%= yield %>
  </main>
  
  <footer>
    <p>Copyright © GeekSalon All Rights Reserved.</p>
  </footer>
</body>
</html>

<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script>
  $(".openbtn").click(function () {
    $(this).toggleClass("active");
    $("#g-nav").toggleClass("panelactive");
  });
  $("#g-nav a").click(function () {
    $(".openbtn").removeClass("active");
    $("#g-nav").removeClass("panelactive");
  });
</script>